ktor:
  application:
    modules:
      - example.com.ApplicationKt.module
  deployment:
    port: 8080

storage:
  user: $POSTGRES_USERNAME
  password: $POSTGRES_PASSWORD
  name: $POSTGRES_DB
  host: $POSTGRES_HOST

jwt:
  domain: "http://0.0.0.0:8080"
  issuer: "http://0.0.0.0:8080"
  audience: "users"
  realm: "ktor-backend"
  secret: $JWT_SECRET