ktor:
  application:
    modules:
      - example.com.ApplicationKt.module
  deployment:
    port: 8080

storage:
  user: $POSTGRES_USERNAME
  password: $POSTGRES_PASSWORD
  name: $POSTGRES_DB
  host: $POSTGRES_HOST